-- Phase 6: Add INSTALLMENT_WAIVED and SYSTEM_NOTE to TimelineEventType enum

ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'INSTALLMENT_WAIVED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'SYSTEM_NOTE';
